/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGraficas;

import com.mycompany.techstore.ServicioDigital;
import com.mycompany.techstore.SistemaProducto;

/**
 *
 * @author pc
 */
public class FrameListarServicios extends javax.swing.JFrame {
    
    private SistemaProducto sistemaProducto;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameListarServicios.class.getName());

    /**
     * Creates new form FrameListarServicios
     */
    public FrameListarServicios(SistemaProducto sistemaProducto) {
        this.sistemaProducto = sistemaProducto;
        initComponents();
        showServices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtListarServicios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtListarServicios.setEditable(false);
        txtListarServicios.setColumns(20);
        txtListarServicios.setRows(5);
        jScrollPane1.setViewportView(txtListarServicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showServices() {
        StringBuilder sb = new StringBuilder();
        sb.append("----- SERVICES LIST -----\n");

        for (ServicioDigital pf : sistemaProducto.getListaServicios().values()) {
            sb.append(pf).append("\n");
        }

        txtListarServicios.setText(sb.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtListarServicios;
    // End of variables declaration//GEN-END:variables
}
