/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGraficas;

import com.mycompany.techstore.SistemaCliente;
import com.mycompany.techstore.Cliente;

/**
 *
 * @author kevin
 */
public class FrameListarClientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameListarClientes.class.getName());

    private SistemaCliente sistemaCliente;
    /**
     * Creates new form FrameListarClientes
     */
    
    public FrameListarClientes(SistemaCliente sistemaCliente) {
        this.sistemaCliente = sistemaCliente;
        initComponents();
        mostrarClientes();
        sistemaCliente.listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtListarClientes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtListarClientes.setEditable(false);
        txtListarClientes.setColumns(20);
        txtListarClientes.setRows(5);
        jScrollPane1.setViewportView(txtListarClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarClientes() {
        StringBuilder sb = new StringBuilder();
        sb.append("----- CLIENTS LIST -----\n");

        for (Cliente c : sistemaCliente.getListaClientes().values()) {
            sb.append(c).append("\n--------------------------------------------\n");
        }

        txtListarClientes.setText(sb.toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtListarClientes;
    // End of variables declaration//GEN-END:variables
}
