/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacesGraficas;

import com.mycompany.techstore.ProductoFisico;
import com.mycompany.techstore.SistemaProducto;

/**
 *
 * @author pc
 */
public class FrameListarProductos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameListarProductos.class.getName());
    
    private SistemaProducto sistemaProducto;

    /**
     * Creates new form FrameListarProductos
     */
    public FrameListarProductos(SistemaProducto sistemaProducto) {
        this.sistemaProducto = sistemaProducto;
        initComponents();
        mostrarProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtListarProductos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtListarProductos.setEditable(false);
        txtListarProductos.setColumns(20);
        txtListarProductos.setRows(5);
        jScrollPane1.setViewportView(txtListarProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarProducto() {
        StringBuilder sb = new StringBuilder();
        sb.append("----- LISTA PRODUCTOS -----\n");

        for (ProductoFisico pf : sistemaProducto.getListaProductos().values()) {
            sb.append(pf).append("\n");
        }

        txtListarProductos.setText(sb.toString());
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtListarProductos;
    // End of variables declaration//GEN-END:variables
}
