/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfacesGraficas;

import com.mycompany.techstore.SistemaProducto;

/**
 *
 * @author pc
 */
public class PanelProducto extends javax.swing.JPanel {
    
    FrameAgregarProducto addProducto;
    FrameListarProductos frListarProductos;
    FrameAgregarServicio addServicio;
    FrameListarServicios frListarServicios;
    
    private SistemaProducto sistemaProducto;

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto(SistemaProducto sistemaProducto) {
        initComponents();
        this.sistemaProducto = sistemaProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListarProductos = new javax.swing.JButton();
        btnAgregarServicio = new javax.swing.JButton();
        btnListarServicios = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));
        setPreferredSize(new java.awt.Dimension(300, 500));

        btnAgregarProducto.setText("Add New Product");
        btnAgregarProducto.setPreferredSize(new java.awt.Dimension(124, 24));
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Producto");

        btnListarProductos.setText("Product List");
        btnListarProductos.setMaximumSize(new java.awt.Dimension(124, 23));
        btnListarProductos.setMinimumSize(new java.awt.Dimension(124, 23));
        btnListarProductos.setPreferredSize(new java.awt.Dimension(115, 24));
        btnListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductosActionPerformed(evt);
            }
        });

        btnAgregarServicio.setText("Add New Service");
        btnAgregarServicio.setMaximumSize(new java.awt.Dimension(124, 23));
        btnAgregarServicio.setMinimumSize(new java.awt.Dimension(124, 23));
        btnAgregarServicio.setPreferredSize(new java.awt.Dimension(115, 24));
        btnAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServicioActionPerformed(evt);
            }
        });

        btnListarServicios.setText("Services List");
        btnListarServicios.setMaximumSize(new java.awt.Dimension(124, 23));
        btnListarServicios.setMinimumSize(new java.awt.Dimension(124, 23));
        btnListarServicios.setPreferredSize(new java.awt.Dimension(115, 24));
        btnListarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarServicios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(btnAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        addProducto = new FrameAgregarProducto(sistemaProducto);
        addProducto.setVisible(true);
        addProducto.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductosActionPerformed
        // TODO add your handling code here:
        frListarProductos = new FrameListarProductos(sistemaProducto);
        frListarProductos.mostrarProducto();
        frListarProductos.setVisible(true);
        frListarProductos.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListarProductosActionPerformed

    private void btnAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServicioActionPerformed
        // TODO add your handling code here:
        addServicio = new FrameAgregarServicio(sistemaProducto);
        addServicio.setVisible(true);
        addServicio.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarServicioActionPerformed

    private void btnListarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarServiciosActionPerformed
        // TODO add your handling code here:
        frListarServicios = new FrameListarServicios(sistemaProducto);
        frListarServicios.setVisible(true);
        frListarServicios.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnListarServiciosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAgregarServicio;
    private javax.swing.JButton btnListarProductos;
    private javax.swing.JButton btnListarServicios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
