/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfacesGraficas;

import com.mycompany.techstore.Cliente;
import com.mycompany.techstore.SistemaCliente;
import interfacesGraficas.AgregarCliente;

/**
 *
 * @author pc
 */
public class PanelCliente extends javax.swing.JPanel {

    AgregarCliente addCliente;
    FrameListarClientes frListarClientes;
    FrameAgregarCompra frAgregarCompra;
    
    
    private SistemaCliente sistemaCliente;
    
    

    public PanelCliente(SistemaCliente sistemaCliente) {
        initComponents();
        this.sistemaCliente = sistemaCliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListarClientes = new javax.swing.JButton();
        btnRegistrarCompra = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 500));

        btnAgregarCliente.setText("Add New Client");
        btnAgregarCliente.setMaximumSize(new java.awt.Dimension(124, 23));
        btnAgregarCliente.setMinimumSize(new java.awt.Dimension(124, 23));
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cliente");

        btnListarClientes.setText("Client List");
        btnListarClientes.setMaximumSize(new java.awt.Dimension(124, 23));
        btnListarClientes.setMinimumSize(new java.awt.Dimension(124, 23));
        btnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClientesActionPerformed(evt);
            }
        });

        btnRegistrarCompra.setText("Register Purchase");
        btnRegistrarCompra.setMaximumSize(new java.awt.Dimension(124, 23));
        btnRegistrarCompra.setMinimumSize(new java.awt.Dimension(124, 23));
        btnRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        addCliente = new AgregarCliente(sistemaCliente);
        addCliente.setVisible(true);
        addCliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClientesActionPerformed
        // TODO add your handling code here:
        frListarClientes = new FrameListarClientes(sistemaCliente);
        frListarClientes.mostrarClientes();
        frListarClientes.setVisible(true);
        frListarClientes.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnListarClientesActionPerformed

    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
        // TODO add your handling code here:
        frAgregarCompra = new FrameAgregarCompra(sistemaCliente);
        frAgregarCompra.setVisible(true);
        frAgregarCompra.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnListarClientes;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
